apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: runner
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: runner
      labels:
        app: runner
    spec:
      volumes:
        - name: buildata
          persistentVolumeClaim:
            claimName: persistent-volume-claim
      containers:
      - image: rheamer/builder
        name: runner
        args: 
        - /bin/sh
        - -c
        - until gradle bootrun; do sleep 10; done
        volumeMounts:
          - mountPath: /build
            name: buildata
